import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "./Navbar";
import { AuthContextProvider } from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          <main className="p-5">{children}</main>
        </AuthContextProvider>
      </body>
    </html>
  );
}
